{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "sys.path.append(\"instagram_stories\")\n",
    "\n",
    "import insta_fetch_tagstory as ift"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Request return 429 error!\n",
      "{'status': 'fail', 'message': 'Please wait a few minutes before you try again.'}\n",
      "Request return 404 error!\n",
      "Login success!\n",
      "\n",
      "{'video_dash_manifest': '<MPD xmlns=\"urn:mpeg:dash:schema:mpd:2011\" minBufferTime=\"PT1.500S\" type=\"static\" mediaPresentationDuration=\"PT0H0M7.872S\" maxSegmentDuration=\"PT0H0M2.000S\" profiles=\"urn:mpeg:dash:profile:isoff-on-demand:2011,http://dashif.org/guidelines/dash264\"><Period duration=\"PT0H0M7.872S\"><AdaptationSet segmentAlignment=\"true\" maxWidth=\"640\" maxHeight=\"854\" maxFrameRate=\"30\" par=\"360:640\" lang=\"und\" subsegmentAlignment=\"true\" subsegmentStartsWithSAP=\"1\"><Representation id=\"18017234200096930vd\" mimeType=\"video/mp4\" codecs=\"avc1.4D401F\" width=\"640\" height=\"1138\" frameRate=\"30\" sar=\"5121:5120\" startWithSAP=\"1\" bandwidth=\"1702119\" FBQualityClass=\"sd\" FBQualityLabel=\"640w\"><BaseURL>https://instagram.fmex6-1.fna.fbcdn.net/vp/e506cda83c038c292361d92914fa22a9/5C656119/t72.14836-16/41191274_2370557636500663_3935200235340729386_n.mp4?_nc_ht=instagram.fmex6-1.fna.fbcdn.net</BaseURL><SegmentBase indexRangeExact=\"true\" indexRange=\"933-1012\" FBFirstSegmentRange=\"1013-409856\" FBSecondSegmentRange=\"409857-817793\"><Initialization range=\"0-932\"/></SegmentBase></Representation><Representation id=\"18033347191011138v\" mimeType=\"video/mp4\" codecs=\"avc1.4D401F\" width=\"480\" height=\"854\" frameRate=\"30\" sar=\"1281:1280\" startWithSAP=\"1\" bandwidth=\"997691\" FBQualityClass=\"sd\" FBQualityLabel=\"480w\"><BaseURL>https://instagram.fmex6-1.fna.fbcdn.net/vp/94e35d994251d9051da539742387fd48/5C65F6FE/t72.14836-16/33902162_402886417152188_8863887011614649010_n.mp4?_nc_ht=instagram.fmex6-1.fna.fbcdn.net</BaseURL><SegmentBase indexRangeExact=\"true\" indexRange=\"932-1011\" FBFirstSegmentRange=\"1012-215993\" FBSecondSegmentRange=\"215994-470398\"><Initialization range=\"0-931\"/></SegmentBase></Representation><Representation id=\"17915805715302544v\" mimeType=\"video/mp4\" codecs=\"avc1.4D401F\" width=\"360\" height=\"640\" frameRate=\"30\" sar=\"1:1\" startWithSAP=\"1\" bandwidth=\"612546\" FBQualityClass=\"sd\" FBQualityLabel=\"360w\"><BaseURL>https://instagram.fmex6-1.fna.fbcdn.net/vp/da41b840af2afa965ec2ac2787502e9e/5C657459/t72.14836-16/35574069_380489892683048_795846965273816797_n.mp4?_nc_ht=instagram.fmex6-1.fna.fbcdn.net</BaseURL><SegmentBase indexRangeExact=\"true\" indexRange=\"912-991\" FBFirstSegmentRange=\"992-117111\" FBSecondSegmentRange=\"117112-283546\"><Initialization range=\"0-911\"/></SegmentBase></Representation></AdaptationSet><AdaptationSet segmentAlignment=\"true\" lang=\"und\" subsegmentAlignment=\"true\" subsegmentStartsWithSAP=\"1\"><Representation id=\"17933658022268250ad\" mimeType=\"audio/mp4\" codecs=\"mp4a.40.2\" audioSamplingRate=\"44100\" startWithSAP=\"1\" bandwidth=\"66931\"><AudioChannelConfiguration schemeIdUri=\"urn:mpeg:dash:23003:3:audio_channel_configuration:2011\" value=\"1\"/><BaseURL>https://instagram.fmex6-1.fna.fbcdn.net/vp/7584e6a0d683f9f0cb4bb200d123d084/5C65C269/t72.14836-16/40846436_395850607648937_968109447213884660_n.mp4?_nc_ht=instagram.fmex6-1.fna.fbcdn.net</BaseURL><SegmentBase indexRangeExact=\"true\" indexRange=\"840-919\" FBFirstSegmentRange=\"920-17576\" FBSecondSegmentRange=\"17577-33956\"><Initialization range=\"0-839\"/></SegmentBase></Representation></AdaptationSet></Period></MPD>', 'has_audio': True, 'original_width': 720, 'expiring_at': 1550082269, 'can_reshare': True, 'is_reel_media': True, 'id': '1977831214652480054_5897174813', 'story_hashtags': [{'rotation': 0.0, 'hashtag': {'name': 'tattoos', 'id': 17843798329061192}, 'is_pinned': 0, 'z': 0, 'x': 0.529262866667762, 'is_hidden': 0, 'height': 0.052129004094253, 'width': 0.20945688697980003, 'y': 0.8498133671055771}], 'show_one_tap_fb_share_tooltip': True, 'caption_position': 0.0, 'video_duration': 7.83, 'media_type': 2, 'code': 'BtyqwK_Clo2', 'device_timestamp': 1549995870422474, 'can_viewer_save': True, 'filter_type': 707, 'photo_of_you': False, 'user': {'username': 'funkyoutattoo', 'profile_pic_id': '1976514539370651514_5897174813', 'is_private': False, 'full_name': '🔥🔥FUNK💉💉YOU💉💉TATTOO🔥🔥', 'is_verified': False, 'pk': 5897174813, 'is_favorite': False, 'profile_pic_url': 'https://instagram.fmex6-1.fna.fbcdn.net/vp/b21a000705de100b4014891d6914f75a/5CFF6245/t51.2885-19/s150x150/50762777_295554644397506_3808871328459522048_n.jpg?_nc_ht=instagram.fmex6-1.fna.fbcdn.net', 'has_anonymous_profile_picture': False, 'is_unpublished': False, 'reel_auto_archive': 'on'}, 'number_of_qualities': 3, 'taken_at': 1549995869, 'video_versions': [{'id': '18032705146042490', 'height': 1136, 'type': 101, 'width': 640, 'url': 'https://instagram.fmex6-1.fna.fbcdn.net/vp/c034b890b9613d95eef7d78108d8cd9c/5C65D2FC/t50.12441-16/52441712_2178242739095107_3654886201228723176_n.mp4?_nc_ht=instagram.fmex6-1.fna.fbcdn.net'}, {'id': '18029065021064831', 'height': 852, 'type': 102, 'width': 480, 'url': 'https://instagram.fmex6-1.fna.fbcdn.net/vp/2fd9e9a5f5bbd860538cf2eb2a74b957/5C65B30C/t50.12441-16/52755165_616627448768155_2104098289264050871_n.mp4?_nc_ht=instagram.fmex6-1.fna.fbcdn.net'}, {'id': '18029065021064831', 'height': 852, 'type': 103, 'width': 480, 'url': 'https://instagram.fmex6-1.fna.fbcdn.net/vp/2fd9e9a5f5bbd860538cf2eb2a74b957/5C65B30C/t50.12441-16/52755165_616627448768155_2104098289264050871_n.mp4?_nc_ht=instagram.fmex6-1.fna.fbcdn.net'}], 'caption_is_edited': False, 'can_reply': True, 'client_cache_key': 'MTk3NzgzMTIxNDY1MjQ4MDA1NA==.2', 'is_dash_eligible': 1, 'original_height': 1280, 'caption': None, 'organic_tracking_token': 'eyJ2ZXJzaW9uIjo1LCJwYXlsb2FkIjp7ImlzX2FuYWx5dGljc190cmFja2VkIjp0cnVlLCJ1dWlkIjoiZWUwZGYyYTg4OWI2NDI0Y2I2NzJjZTRlZTdlNzkzYTUxOTc3ODMxMjE0NjUyNDgwMDU0Iiwic2VydmVyX3Rva2VuIjoiMTU1MDAwMzI1NzI3M3wxOTc3ODMxMjE0NjUyNDgwMDU0fDQwNDc5MjM4NzJ8ZDkyMTFjMmUyNjU3ZWEwMmRiYjQxZTNjNDBjMGYzZGQwYjZjMGYzN2JjZDQ2ZWQ0OTQxNzhmOTg5NzhkYjI0MCJ9LCJzaWduYXR1cmUiOiIifQ==', 'image_versions2': {'candidates': [{'height': 1137, 'width': 640, 'url': 'https://instagram.fmex6-1.fna.fbcdn.net/vp/4516c21c30f6099f1c337c2875e9c5d9/5C65812A/t51.12442-15/e15/p640x640/51506966_309776523011739_5974985117257316048_n.jpg?_nc_ht=instagram.fmex6-1.fna.fbcdn.net'}, {'height': 426, 'width': 240, 'url': 'https://instagram.fmex6-1.fna.fbcdn.net/vp/0107c2f4f533b7c9dbfaef1212083ea1/5C65EF3F/t51.12442-15/e15/p240x240/51506966_309776523011739_5974985117257316048_n.jpg?_nc_ht=instagram.fmex6-1.fna.fbcdn.net'}]}, 'pk': 1977831214652480054, 'video_codec': 'avc1.4D401F', 'supports_reel_reactions': True, 'has_shared_to_fb': 0}\n",
      "====================================================================================================\n",
      "{'video_dash_manifest': '<MPD xmlns=\"urn:mpeg:dash:schema:mpd:2011\" minBufferTime=\"PT1.500S\" type=\"static\" mediaPresentationDuration=\"PT0H0M4.900S\" maxSegmentDuration=\"PT0H0M2.900S\" profiles=\"urn:mpeg:dash:profile:isoff-on-demand:2011,http://dashif.org/guidelines/dash264\"><Period duration=\"PT0H0M4.900S\"><AdaptationSet segmentAlignment=\"true\" maxWidth=\"480\" maxHeight=\"852\" maxFrameRate=\"30\" par=\"480:852\" lang=\"und\" subsegmentAlignment=\"true\" subsegmentStartsWithSAP=\"1\"><Representation id=\"17941247635252698vd\" mimeType=\"video/mp4\" codecs=\"avc1.4D401F\" width=\"480\" height=\"852\" frameRate=\"30\" sar=\"1:1\" startWithSAP=\"1\" bandwidth=\"218365\" FBQualityClass=\"sd\" FBQualityLabel=\"480w\"><BaseURL>https://instagram.fmex6-1.fna.fbcdn.net/vp/f3c051f801fe5c4953761633040b81c1/5C65A073/t72.14836-16/40862137_841734169499545_3098724747020312228_n.mp4?_nc_ht=instagram.fmex6-1.fna.fbcdn.net</BaseURL><SegmentBase indexRangeExact=\"true\" indexRange=\"906-961\" FBFirstSegmentRange=\"962-49415\" FBSecondSegmentRange=\"49416-133748\"><Initialization range=\"0-905\"/></SegmentBase></Representation></AdaptationSet></Period></MPD>', 'has_audio': False, 'original_width': 540, 'expiring_at': 1550082405, 'can_reshare': False, 'is_reel_media': True, 'id': '1977832339767394701_1580924767', 'story_hashtags': [{'rotation': 0.94593227, 'hashtag': {'name': 'tattoos', 'id': 17843798329061192}, 'is_pinned': 0, 'z': 2, 'x': 0.7650062400000001, 'is_hidden': 0, 'height': 0.09993512, 'width': 0.46695277, 'y': 0.8103328999999999}], 'show_one_tap_fb_share_tooltip': True, 'caption_position': 0.0, 'video_duration': 4.87, 'media_type': 2, 'code': 'BtyrAi1HYGN', 'device_timestamp': 301120095812894, 'can_viewer_save': True, 'filter_type': 0, 'photo_of_you': False, 'user': {'username': 'yaneth.guzman7', 'profile_pic_id': '1977219889803563406_1580924767', 'is_private': False, 'full_name': '💙🐍VENENO🐍💙', 'is_verified': False, 'pk': 1580924767, 'is_favorite': False, 'profile_pic_url': 'https://instagram.fmex6-1.fna.fbcdn.net/vp/cdb8ab5228f11cbbcbf9561e4f698fb8/5CEC3530/t51.2885-19/s150x150/50919743_813033819047060_5557244350204739584_n.jpg?_nc_ht=instagram.fmex6-1.fna.fbcdn.net', 'has_anonymous_profile_picture': False, 'is_unpublished': False, 'reel_auto_archive': 'on'}, 'number_of_qualities': 1, 'taken_at': 1549996005, 'video_versions': [{'id': '18031875493019313', 'height': 852, 'type': 101, 'width': 480, 'url': 'https://instagram.fmex6-1.fna.fbcdn.net/vp/48c174199e35e2bb9652cc7b6101fb63/5C658E8F/t50.12441-16/52366875_101692014284111_3076767343448786288_n.mp4?_nc_ht=instagram.fmex6-1.fna.fbcdn.net'}, {'id': '18031875493019313', 'height': 852, 'type': 102, 'width': 480, 'url': 'https://instagram.fmex6-1.fna.fbcdn.net/vp/48c174199e35e2bb9652cc7b6101fb63/5C658E8F/t50.12441-16/52366875_101692014284111_3076767343448786288_n.mp4?_nc_ht=instagram.fmex6-1.fna.fbcdn.net'}, {'id': '18031875493019313', 'height': 852, 'type': 103, 'width': 480, 'url': 'https://instagram.fmex6-1.fna.fbcdn.net/vp/48c174199e35e2bb9652cc7b6101fb63/5C658E8F/t50.12441-16/52366875_101692014284111_3076767343448786288_n.mp4?_nc_ht=instagram.fmex6-1.fna.fbcdn.net'}], 'caption_is_edited': False, 'can_reply': False, 'client_cache_key': 'MTk3NzgzMjMzOTc2NzM5NDcwMQ==.2', 'is_dash_eligible': 1, 'original_height': 960, 'caption': None, 'organic_tracking_token': 'eyJ2ZXJzaW9uIjo1LCJwYXlsb2FkIjp7ImlzX2FuYWx5dGljc190cmFja2VkIjp0cnVlLCJ1dWlkIjoiZWUwZGYyYTg4OWI2NDI0Y2I2NzJjZTRlZTdlNzkzYTUxOTc3ODMyMzM5NzY3Mzk0NzAxIiwic2VydmVyX3Rva2VuIjoiMTU1MDAwMzI1NzI3OXwxOTc3ODMyMzM5NzY3Mzk0NzAxfDQwNDc5MjM4NzJ8ODAwOGU5MmFjNDc1MjNlZWZiZjVkNDMwMjkwZjY0ZmE1YzY5ZDQ1MTRkOWQzN2JlMjhhNjZmNDlhZWQwYmE2NyJ9LCJzaWduYXR1cmUiOiIifQ==', 'reel_mentions': [{'rotation': -0.047005706, 'user': {'username': 'nikolatattoo.petkovic', 'profile_pic_id': '1971901799054379140_1392397640', 'is_private': False, 'full_name': '🇷🇸 NIKOLA PETKOVIĆ 🇩🇪', 'is_verified': False, 'pk': 1392397640, 'profile_pic_url': 'https://instagram.fmex6-1.fna.fbcdn.net/vp/746062c8047e728a9480de6c0e84ff51/5CE5974E/t51.2885-19/s150x150/50154930_1665693370396600_2481518166736371712_n.jpg?_nc_ht=instagram.fmex6-1.fna.fbcdn.net'}, 'is_pinned': 0, 'z': 1, 'x': 0.3309989, 'is_hidden': 0, 'height': 0.06522205, 'width': 0.5, 'y': 0.7919923999999999}, {'rotation': -0.030321684, 'user': {'username': 'nikolatattoo.petkovic', 'profile_pic_id': '1971901799054379140_1392397640', 'is_private': False, 'full_name': '🇷🇸 NIKOLA PETKOVIĆ 🇩🇪', 'is_verified': False, 'pk': 1392397640, 'profile_pic_url': 'https://instagram.fmex6-1.fna.fbcdn.net/vp/746062c8047e728a9480de6c0e84ff51/5CE5974E/t51.2885-19/s150x150/50154930_1665693370396600_2481518166736371712_n.jpg?_nc_ht=instagram.fmex6-1.fna.fbcdn.net'}, 'is_pinned': 0, 'z': 0, 'x': 0.54989606, 'is_hidden': 0, 'height': 0.5, 'width': 0.5, 'y': 0.43850133}], 'image_versions2': {'candidates': [{'height': 960, 'width': 540, 'url': 'https://instagram.fmex6-1.fna.fbcdn.net/vp/810ad866c537e54e05afb05229ecb2e7/5C655E3F/t51.12442-15/e35/50584877_413644636048264_5452663838788805137_n.jpg?_nc_ht=instagram.fmex6-1.fna.fbcdn.net'}, {'height': 426, 'width': 240, 'url': 'https://instagram.fmex6-1.fna.fbcdn.net/vp/637ccfd6c5c92ad933f3390e992c6296/5C65FD67/t51.12442-15/e35/p240x240/50584877_413644636048264_5452663838788805137_n.jpg?_nc_ht=instagram.fmex6-1.fna.fbcdn.net'}]}, 'imported_taken_at': 1549995815, 'pk': 1977832339767394701, 'video_codec': 'avc1.4D401F', 'supports_reel_reactions': True, 'has_shared_to_fb': 0}\n",
      "====================================================================================================\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'video_dash_manifest': '<MPD xmlns=\"urn:mpeg:dash:schema:mpd:2011\" minBufferTime=\"PT1.500S\" type=\"static\" mediaPresentationDuration=\"PT0H0M9.467S\" maxSegmentDuration=\"PT0H0M2.000S\" profiles=\"urn:mpeg:dash:profile:isoff-on-demand:2011,http://dashif.org/guidelines/dash264\"><Period duration=\"PT0H0M9.467S\"><AdaptationSet segmentAlignment=\"true\" maxWidth=\"640\" maxHeight=\"798\" maxFrameRate=\"30\" par=\"480:798\" lang=\"und\" subsegmentAlignment=\"true\" subsegmentStartsWithSAP=\"1\"><Representation id=\"18001147954159096vd\" mimeType=\"video/mp4\" codecs=\"avc1.4D401F\" width=\"640\" height=\"1064\" frameRate=\"30\" sar=\"1:1\" startWithSAP=\"1\" bandwidth=\"1598081\" FBQualityClass=\"sd\" FBQualityLabel=\"640w\"><BaseURL>https://instagram.fmex6-1.fna.fbcdn.net/vp/48ec3a2e7a2f52dbb5cd40bcbb37b7dd/5C656A39/t72.14836-16/35133479_402251173681083_4775459144877708024_n.mp4?_nc_ht=instagram.fmex6-1.fna.fbcdn.net</BaseURL><SegmentBase indexRangeExact=\"true\" indexRange=\"910-1001\" FBFirstSegmentRange=\"1002-249061\" FBSecondSegmentRange=\"249062-729193\"><Initialization range=\"0-909\"/></SegmentBase></Representation><Representation id=\"18033548455031214v\" mimeType=\"video/mp4\" codecs=\"avc1.4D401F\" width=\"480\" height=\"798\" frameRate=\"30\" sar=\"1:1\" startWithSAP=\"1\" bandwidth=\"1019623\" FBQualityClass=\"sd\" FBQualityLabel=\"480w\"><BaseURL>https://instagram.fmex6-1.fna.fbcdn.net/vp/712e8e1a690922c4cee612992c83d6bb/5C65AB80/t72.14836-16/27446795_323507778285040_8400511564490990227_n.mp4?_nc_ht=instagram.fmex6-1.fna.fbcdn.net</BaseURL><SegmentBase indexRangeExact=\"true\" indexRange=\"910-1001\" FBFirstSegmentRange=\"1002-147658\" FBSecondSegmentRange=\"147659-448207\"><Initialization range=\"0-909\"/></SegmentBase></Representation></AdaptationSet></Period></MPD>', 'has_audio': False, 'original_width': 720, 'expiring_at': 1550082850, 'can_reshare': True, 'is_reel_media': True, 'id': '1977836084616734477_3696767249', 'story_hashtags': [{'rotation': 0.0, 'hashtag': {'name': 'tattoos', 'id': 17843798329061192}, 'is_pinned': 0, 'z': 0, 'x': 0.10677858, 'is_hidden': 0, 'height': 0.09643255, 'width': 0.41851849999999996, 'y': 0.9466132500000001}], 'show_one_tap_fb_share_tooltip': True, 'caption_position': 0.0, 'video_duration': 9.45, 'media_type': 2, 'code': 'Btyr3Cfh6cN', 'device_timestamp': 38279774333634, 'can_viewer_save': True, 'filter_type': 0, 'photo_of_you': False, 'user': {'username': 'rogan_tattoo', 'profile_pic_id': '1975036246154982208_3696767249', 'is_private': False, 'full_name': 'Luke Rogan', 'is_verified': False, 'pk': 3696767249, 'is_favorite': False, 'profile_pic_url': 'https://instagram.fmex6-1.fna.fbcdn.net/vp/cea62323e704c5c5437dd310ecba9cb0/5CFE8DE6/t51.2885-19/s150x150/51813513_2242834382396468_7961262872921636864_n.jpg?_nc_ht=instagram.fmex6-1.fna.fbcdn.net', 'has_anonymous_profile_picture': False, 'is_unpublished': False, 'reel_auto_archive': 'on'}, 'number_of_qualities': 2, 'taken_at': 1549996450, 'video_versions': [{'id': '17856575071338119', 'height': 1062, 'type': 101, 'width': 640, 'url': 'https://instagram.fmex6-1.fna.fbcdn.net/vp/20e8926abb70d33bd16009791223e2cf/5C655CD4/t50.12441-16/52235112_257440795175230_8954702247350054602_n.mp4?_nc_ht=instagram.fmex6-1.fna.fbcdn.net'}, {'id': '17859390868329388', 'height': 796, 'type': 102, 'width': 480, 'url': 'https://instagram.fmex6-1.fna.fbcdn.net/vp/0e58264b9165d6bd15ef5812790fa0b4/5C65CA0B/t50.12441-16/52561244_2234589716754305_808648022984182599_n.mp4?_nc_ht=instagram.fmex6-1.fna.fbcdn.net'}, {'id': '17859390868329388', 'height': 796, 'type': 103, 'width': 480, 'url': 'https://instagram.fmex6-1.fna.fbcdn.net/vp/0e58264b9165d6bd15ef5812790fa0b4/5C65CA0B/t50.12441-16/52561244_2234589716754305_808648022984182599_n.mp4?_nc_ht=instagram.fmex6-1.fna.fbcdn.net'}], 'caption_is_edited': False, 'can_reply': True, 'client_cache_key': 'MTk3NzgzNjA4NDYxNjczNDQ3Nw==.2', 'is_dash_eligible': 1, 'original_height': 1196, 'caption': None, 'organic_tracking_token': 'eyJ2ZXJzaW9uIjo1LCJwYXlsb2FkIjp7ImlzX2FuYWx5dGljc190cmFja2VkIjpmYWxzZSwidXVpZCI6ImVlMGRmMmE4ODliNjQyNGNiNjcyY2U0ZWU3ZTc5M2E1MTk3NzgzNjA4NDYxNjczNDQ3NyIsInNlcnZlcl90b2tlbiI6IjE1NTAwMDMyNTcyNjJ8MTk3NzgzNjA4NDYxNjczNDQ3N3w0MDQ3OTIzODcyfGQ4NWVjZjVlZTQyNTZlZjI5MDllMDZhNTBhZjUzNDc0NDExNmJkMmI4ZTBmNDFjMTIzNDY2ZDQ3YjI0Y2UyZTUifSwic2lnbmF0dXJlIjoiIn0=', 'reel_mentions': [{'rotation': 0.0, 'user': {'username': 'rogan_tattoo', 'profile_pic_id': '1975036246154982208_3696767249', 'is_private': False, 'full_name': 'Luke Rogan', 'is_verified': False, 'pk': 3696767249, 'profile_pic_url': 'https://instagram.fmex6-1.fna.fbcdn.net/vp/cea62323e704c5c5437dd310ecba9cb0/5CFE8DE6/t51.2885-19/s150x150/51813513_2242834382396468_7961262872921636864_n.jpg?_nc_ht=instagram.fmex6-1.fna.fbcdn.net'}, 'is_pinned': 0, 'z': 1, 'x': 0.30613965, 'is_hidden': 0, 'height': 0.09587514, 'width': 0.5, 'y': 0.23234044}], 'image_versions2': {'candidates': [{'height': 1196, 'width': 720, 'url': 'https://instagram.fmex6-1.fna.fbcdn.net/vp/c911c0c2a34f9a8b913e89208fe20b5f/5C65986F/t51.12442-15/e35/50686248_731328930601352_77357855118410477_n.jpg?_nc_ht=instagram.fmex6-1.fna.fbcdn.net'}, {'height': 398, 'width': 240, 'url': 'https://instagram.fmex6-1.fna.fbcdn.net/vp/d32b146e711efb5ef0a7f215a3bd50d2/5C65C43C/t51.12442-15/e35/p240x240/50686248_731328930601352_77357855118410477_n.jpg?_nc_ht=instagram.fmex6-1.fna.fbcdn.net'}]}, 'pk': 1977836084616734477, 'video_codec': 'avc1.4D401F', 'supports_reel_reactions': True, 'has_shared_to_fb': 3}\n",
      "====================================================================================================\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:CRITICAL ERROR uploading posts for: tattoos\n",
      "Traceback (most recent call last):\n",
      "  File \"instagram_stories/insta_fetch_tagstory.py\", line 94, in main\n",
      "    is3.save_story(d['video_url'],s3dir,d['insta_id2'],path)\n",
      "  File \"instagram_stories/insta_s3.py\", line 26, in save_story\n",
      "    save_s3(path,insta_id,type_, bucket_name = bucket_name)\n",
      "  File \"instagram_stories/insta_s3.py\", line 22, in save_s3\n",
      "    return s3.Object(bucket_name, type_+'/'+file_without_path).put(Body=open(file_name, 'rb'),ContentType = ct)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/boto3/resources/factory.py\", line 520, in do_action\n",
      "    response = action(self, *args, **kwargs)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/boto3/resources/action.py\", line 83, in __call__\n",
      "    response = getattr(parent.meta.client, operation_name)(**params)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/botocore/client.py\", line 314, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/botocore/client.py\", line 599, in _make_api_call\n",
      "    operation_model, request_dict)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/botocore/endpoint.py\", line 148, in make_request\n",
      "    return self._send_request(request_dict, operation_model)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/botocore/endpoint.py\", line 188, in _send_request\n",
      "    request, operation_model, attempts)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/botocore/endpoint.py\", line 222, in _get_response\n",
      "    proxies=self.proxies, timeout=self.timeout)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/botocore/vendored/requests/sessions.py\", line 573, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/botocore/vendored/requests/adapters.py\", line 370, in send\n",
      "    timeout=timeout\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py\", line 544, in urlopen\n",
      "    body=body, headers=headers)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py\", line 349, in _make_request\n",
      "    conn.request(method, url, **httplib_request_kw)\n",
      "  File \"/usr/lib/python3.5/http/client.py\", line 1106, in request\n",
      "    self._send_request(method, url, body, headers)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/botocore/awsrequest.py\", line 130, in _send_request\n",
      "    self, method, url, body, headers, *args, **kwargs)\n",
      "  File \"/usr/lib/python3.5/http/client.py\", line 1151, in _send_request\n",
      "    self.endheaders(body)\n",
      "  File \"/usr/lib/python3.5/http/client.py\", line 1102, in endheaders\n",
      "    self._send_output(message_body)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/botocore/awsrequest.py\", line 165, in _send_output\n",
      "    self._handle_expect_response(message_body)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/botocore/awsrequest.py\", line 208, in _handle_expect_response\n",
      "    self._send_message_body(message_body)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/botocore/awsrequest.py\", line 235, in _send_message_body\n",
      "    self.send(message_body)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/botocore/awsrequest.py\", line 242, in send\n",
      "    return HTTPConnection.send(self, str)\n",
      "  File \"/usr/lib/python3.5/http/client.py\", line 905, in send\n",
      "    self.sock.sendall(datablock)\n",
      "  File \"/usr/lib/python3.5/ssl.py\", line 891, in sendall\n",
      "    v = self.send(data[count:])\n",
      "  File \"/usr/lib/python3.5/ssl.py\", line 861, in send\n",
      "    return self._sslobj.write(data)\n",
      "  File \"/usr/lib/python3.5/ssl.py\", line 586, in write\n",
      "    return self._sslobj.write(data)\n",
      "KeyboardInterrupt\n",
      "ERROR:root:CRITICAL ERROR uploading posts for: tattoo\n",
      "Traceback (most recent call last):\n",
      "  File \"instagram_stories/insta_fetch_tagstory.py\", line 69, in main\n",
      "    posts_story = insta.get_tag_feed(tag, API,type_ = 'story')\n",
      "  File \"instagram_stories/insta_scraper.py\", line 107, in get_tag_feed\n",
      "    API.tagFeed(tag) # get media list by tag\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/InstagramAPI/InstagramAPI.py\", line 623, in tagFeed\n",
      "    userFeed = self.SendRequest('feed/tag/' + str(tag) + '/?rank_token=' + str(self.rank_token) + '&ranked_content=true&')\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/InstagramAPI/InstagramAPI.py\", line 837, in SendRequest\n",
      "    response = self.s.get(self.API_URL + endpoint, verify=verify)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/requests/sessions.py\", line 546, in get\n",
      "    return self.request('GET', url, **kwargs)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/requests/sessions.py\", line 533, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/requests/sessions.py\", line 646, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/requests/adapters.py\", line 449, in send\n",
      "    timeout=timeout\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/urllib3/connectionpool.py\", line 600, in urlopen\n",
      "    chunked=chunked)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/urllib3/connectionpool.py\", line 343, in _make_request\n",
      "    self._validate_conn(conn)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/urllib3/connectionpool.py\", line 839, in _validate_conn\n",
      "    conn.connect()\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/urllib3/connection.py\", line 301, in connect\n",
      "    conn = self._new_conn()\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/urllib3/connection.py\", line 159, in _new_conn\n",
      "    (self._dns_host, self.port), self.timeout, **extra_kw)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/urllib3/util/connection.py\", line 57, in create_connection\n",
      "    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):\n",
      "  File \"/usr/lib/python3.5/socket.py\", line 732, in getaddrinfo\n",
      "    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\n",
      "KeyboardInterrupt\n",
      "From cffi callback <function _verify_callback at 0x7f545afb79d8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/OpenSSL/SSL.py\", line 306, in wrapper\n",
      "    @wraps(callback)\n",
      "KeyboardInterrupt\n",
      "WARNING:py.warnings:/home/ubuntu/.local/lib/python3.5/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n",
      "  InsecureRequestWarning)\n",
      "\n",
      "ERROR:root:CRITICAL ERROR uploading posts for: tatuajes\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/urllib3/connectionpool.py\", line 377, in _make_request\n",
      "    httplib_response = conn.getresponse(buffering=True)\n",
      "TypeError: getresponse() got an unexpected keyword argument 'buffering'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"instagram_stories/insta_fetch_tagstory.py\", line 69, in main\n",
      "    posts_story = insta.get_tag_feed(tag, API,type_ = 'story')\n",
      "  File \"instagram_stories/insta_scraper.py\", line 107, in get_tag_feed\n",
      "    API.tagFeed(tag) # get media list by tag\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/InstagramAPI/InstagramAPI.py\", line 623, in tagFeed\n",
      "    userFeed = self.SendRequest('feed/tag/' + str(tag) + '/?rank_token=' + str(self.rank_token) + '&ranked_content=true&')\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/InstagramAPI/InstagramAPI.py\", line 837, in SendRequest\n",
      "    response = self.s.get(self.API_URL + endpoint, verify=verify)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/requests/sessions.py\", line 546, in get\n",
      "    return self.request('GET', url, **kwargs)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/requests/sessions.py\", line 533, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/requests/sessions.py\", line 646, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/requests/adapters.py\", line 449, in send\n",
      "    timeout=timeout\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/urllib3/connectionpool.py\", line 600, in urlopen\n",
      "    chunked=chunked)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/urllib3/connectionpool.py\", line 380, in _make_request\n",
      "    httplib_response = conn.getresponse()\n",
      "  File \"/usr/lib/python3.5/http/client.py\", line 1197, in getresponse\n",
      "    response.begin()\n",
      "  File \"/usr/lib/python3.5/http/client.py\", line 297, in begin\n",
      "    version, status, reason = self._read_status()\n",
      "  File \"/usr/lib/python3.5/http/client.py\", line 258, in _read_status\n",
      "    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n",
      "  File \"/usr/lib/python3.5/socket.py\", line 575, in readinto\n",
      "    return self._sock.recv_into(b)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/urllib3/contrib/pyopenssl.py\", line 294, in recv_into\n",
      "    return self.connection.recv_into(*args, **kwargs)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/OpenSSL/SSL.py\", line 1813, in recv_into\n",
      "    result = _lib.SSL_read(self._ssl, buf, nbytes)\n",
      "KeyboardInterrupt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:CRITICAL ERROR uploading posts for: tatuaje\n",
      "Traceback (most recent call last):\n",
      "  File \"instagram_stories/insta_fetch_tagstory.py\", line 69, in main\n",
      "    posts_story = insta.get_tag_feed(tag, API,type_ = 'story')\n",
      "  File \"instagram_stories/insta_scraper.py\", line 107, in get_tag_feed\n",
      "    API.tagFeed(tag) # get media list by tag\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/InstagramAPI/InstagramAPI.py\", line 623, in tagFeed\n",
      "    userFeed = self.SendRequest('feed/tag/' + str(tag) + '/?rank_token=' + str(self.rank_token) + '&ranked_content=true&')\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/InstagramAPI/InstagramAPI.py\", line 837, in SendRequest\n",
      "    response = self.s.get(self.API_URL + endpoint, verify=verify)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/requests/sessions.py\", line 546, in get\n",
      "    return self.request('GET', url, **kwargs)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/requests/sessions.py\", line 533, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/requests/sessions.py\", line 646, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/requests/adapters.py\", line 449, in send\n",
      "    timeout=timeout\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/urllib3/connectionpool.py\", line 600, in urlopen\n",
      "    chunked=chunked)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/urllib3/connectionpool.py\", line 343, in _make_request\n",
      "    self._validate_conn(conn)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/urllib3/connectionpool.py\", line 839, in _validate_conn\n",
      "    conn.connect()\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/urllib3/connection.py\", line 344, in connect\n",
      "    ssl_context=context)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/urllib3/util/ssl_.py\", line 344, in ssl_wrap_socket\n",
      "    return context.wrap_socket(sock, server_hostname=server_hostname)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/urllib3/contrib/pyopenssl.py\", line 453, in wrap_socket\n",
      "    cnx.do_handshake()\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/OpenSSL/SSL.py\", line 1906, in do_handshake\n",
      "    result = _lib.SSL_do_handshake(self._ssl)\n",
      "KeyboardInterrupt\n",
      "WARNING:py.warnings:/home/ubuntu/.local/lib/python3.5/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n",
      "  InsecureRequestWarning)\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/urllib3/connectionpool.py\", line 377, in _make_request\n",
      "    httplib_response = conn.getresponse(buffering=True)\n",
      "TypeError: getresponse() got an unexpected keyword argument 'buffering'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py\", line 2963, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-2-c77f0bfc6f1e>\", line 1, in <module>\n",
      "    ift.main('tattoos')\n",
      "  File \"instagram_stories/insta_fetch_tagstory.py\", line 107, in main\n",
      "    API.logout()\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/InstagramAPI/InstagramAPI.py\", line 139, in logout\n",
      "    logout = self.SendRequest('accounts/logout/')\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/InstagramAPI/InstagramAPI.py\", line 837, in SendRequest\n",
      "    response = self.s.get(self.API_URL + endpoint, verify=verify)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/requests/sessions.py\", line 546, in get\n",
      "    return self.request('GET', url, **kwargs)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/requests/sessions.py\", line 533, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/requests/sessions.py\", line 646, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/requests/adapters.py\", line 449, in send\n",
      "    timeout=timeout\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/urllib3/connectionpool.py\", line 600, in urlopen\n",
      "    chunked=chunked)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/urllib3/connectionpool.py\", line 380, in _make_request\n",
      "    httplib_response = conn.getresponse()\n",
      "  File \"/usr/lib/python3.5/http/client.py\", line 1197, in getresponse\n",
      "    response.begin()\n",
      "  File \"/usr/lib/python3.5/http/client.py\", line 297, in begin\n",
      "    version, status, reason = self._read_status()\n",
      "  File \"/usr/lib/python3.5/http/client.py\", line 258, in _read_status\n",
      "    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n",
      "  File \"/usr/lib/python3.5/socket.py\", line 575, in readinto\n",
      "    return self._sock.recv_into(b)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/urllib3/contrib/pyopenssl.py\", line 294, in recv_into\n",
      "    return self.connection.recv_into(*args, **kwargs)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/OpenSSL/SSL.py\", line 1813, in recv_into\n",
      "    result = _lib.SSL_read(self._ssl, buf, nbytes)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py\", line 1863, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/IPython/core/ultratb.py\", line 1095, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/IPython/core/ultratb.py\", line 311, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/IPython/core/ultratb.py\", line 345, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/usr/lib/python3.5/inspect.py\", line 1453, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/usr/lib/python3.5/inspect.py\", line 1410, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/usr/lib/python3.5/inspect.py\", line 672, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/usr/lib/python3.5/inspect.py\", line 718, in getmodule\n",
      "    os.path.realpath(f)] = module.__name__\n",
      "  File \"/usr/lib/python3.5/posixpath.py\", line 373, in realpath\n",
      "    return abspath(path)\n",
      "  File \"/usr/lib/python3.5/posixpath.py\", line 363, in abspath\n",
      "    return normpath(path)\n",
      "  File \"/usr/lib/python3.5/posixpath.py\", line 338, in normpath\n",
      "    comps = path.split(sep)\n",
      "KeyboardInterrupt\n"
     ]
    },
    {
     "ename": "TypeError",
     "evalue": "Can't convert 'list' object to str implicitly",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m~/.local/lib/python3.5/site-packages/urllib3/connectionpool.py\u001b[0m in \u001b[0;36m_make_request\u001b[0;34m(self, conn, method, url, timeout, chunked, **httplib_request_kw)\u001b[0m\n\u001b[1;32m    376\u001b[0m             \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m  \u001b[0;31m# Python 2.7, use buffering of HTTP responses\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 377\u001b[0;31m                 \u001b[0mhttplib_response\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mconn\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mgetresponse\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mbuffering\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mTrue\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    378\u001b[0m             \u001b[0;32mexcept\u001b[0m \u001b[0mTypeError\u001b[0m\u001b[0;34m:\u001b[0m  \u001b[0;31m# Python 3\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mTypeError\u001b[0m: getresponse() got an unexpected keyword argument 'buffering'",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "\u001b[0;32m/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py\u001b[0m in \u001b[0;36mrun_code\u001b[0;34m(self, code_obj, result)\u001b[0m\n\u001b[1;32m   2962\u001b[0m                 \u001b[0;31m#rprint('Running code', repr(code_obj)) # dbg\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 2963\u001b[0;31m                 \u001b[0mexec\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mcode_obj\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0muser_global_ns\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0muser_ns\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   2964\u001b[0m             \u001b[0;32mfinally\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m<ipython-input-2-c77f0bfc6f1e>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mift\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmain\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'tattoos'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m~/Documents/repos/social_networks/instagram_stories/insta_fetch_tagstory.py\u001b[0m in \u001b[0;36mmain\u001b[0;34m(tema)\u001b[0m\n\u001b[1;32m    106\u001b[0m                 \u001b[0mlogging\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mexception\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'CRITICAL ERROR uploading posts for: {}'\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mformat\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mtag\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0mstr\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0msys\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mexc_info\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 107\u001b[0;31m     \u001b[0mAPI\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mlogout\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    108\u001b[0m     \u001b[0mlogger\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0minfo\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Finished!!\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.5/site-packages/InstagramAPI/InstagramAPI.py\u001b[0m in \u001b[0;36mlogout\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    138\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0mlogout\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 139\u001b[0;31m         \u001b[0mlogout\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mSendRequest\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'accounts/logout/'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    140\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.5/site-packages/InstagramAPI/InstagramAPI.py\u001b[0m in \u001b[0;36mSendRequest\u001b[0;34m(self, endpoint, post, login)\u001b[0m\n\u001b[1;32m    836\u001b[0m                 \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 837\u001b[0;31m                     \u001b[0mresponse\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0ms\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mAPI_URL\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0mendpoint\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mverify\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mverify\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    838\u001b[0m                 \u001b[0;32mbreak\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.5/site-packages/requests/sessions.py\u001b[0m in \u001b[0;36mget\u001b[0;34m(self, url, **kwargs)\u001b[0m\n\u001b[1;32m    545\u001b[0m         \u001b[0mkwargs\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msetdefault\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'allow_redirects'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;32mTrue\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 546\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mrequest\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'GET'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0murl\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    547\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.5/site-packages/requests/sessions.py\u001b[0m in \u001b[0;36mrequest\u001b[0;34m(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)\u001b[0m\n\u001b[1;32m    532\u001b[0m         \u001b[0msend_kwargs\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mupdate\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0msettings\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 533\u001b[0;31m         \u001b[0mresp\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msend\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mprep\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0msend_kwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    534\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.5/site-packages/requests/sessions.py\u001b[0m in \u001b[0;36msend\u001b[0;34m(self, request, **kwargs)\u001b[0m\n\u001b[1;32m    645\u001b[0m         \u001b[0;31m# Send the request\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 646\u001b[0;31m         \u001b[0mr\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0madapter\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msend\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mrequest\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    647\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.5/site-packages/requests/adapters.py\u001b[0m in \u001b[0;36msend\u001b[0;34m(self, request, stream, timeout, verify, cert, proxies)\u001b[0m\n\u001b[1;32m    448\u001b[0m                     \u001b[0mretries\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmax_retries\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 449\u001b[0;31m                     \u001b[0mtimeout\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mtimeout\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    450\u001b[0m                 )\n",
      "\u001b[0;32m~/.local/lib/python3.5/site-packages/urllib3/connectionpool.py\u001b[0m in \u001b[0;36murlopen\u001b[0;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)\u001b[0m\n\u001b[1;32m    599\u001b[0m                                                   \u001b[0mbody\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mbody\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mheaders\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mheaders\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 600\u001b[0;31m                                                   chunked=chunked)\n\u001b[0m\u001b[1;32m    601\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.5/site-packages/urllib3/connectionpool.py\u001b[0m in \u001b[0;36m_make_request\u001b[0;34m(self, conn, method, url, timeout, chunked, **httplib_request_kw)\u001b[0m\n\u001b[1;32m    379\u001b[0m                 \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 380\u001b[0;31m                     \u001b[0mhttplib_response\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mconn\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mgetresponse\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    381\u001b[0m                 \u001b[0;32mexcept\u001b[0m \u001b[0mException\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/lib/python3.5/http/client.py\u001b[0m in \u001b[0;36mgetresponse\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   1196\u001b[0m             \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1197\u001b[0;31m                 \u001b[0mresponse\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mbegin\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1198\u001b[0m             \u001b[0;32mexcept\u001b[0m \u001b[0mConnectionError\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/lib/python3.5/http/client.py\u001b[0m in \u001b[0;36mbegin\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    296\u001b[0m         \u001b[0;32mwhile\u001b[0m \u001b[0;32mTrue\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 297\u001b[0;31m             \u001b[0mversion\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mstatus\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mreason\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_read_status\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    298\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mstatus\u001b[0m \u001b[0;34m!=\u001b[0m \u001b[0mCONTINUE\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/lib/python3.5/http/client.py\u001b[0m in \u001b[0;36m_read_status\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    257\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0m_read_status\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 258\u001b[0;31m         \u001b[0mline\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mstr\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfp\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mreadline\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0m_MAXLINE\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0;36m1\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"iso-8859-1\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    259\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mlen\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mline\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;34m>\u001b[0m \u001b[0m_MAXLINE\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/lib/python3.5/socket.py\u001b[0m in \u001b[0;36mreadinto\u001b[0;34m(self, b)\u001b[0m\n\u001b[1;32m    574\u001b[0m             \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 575\u001b[0;31m                 \u001b[0;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_sock\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mrecv_into\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mb\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    576\u001b[0m             \u001b[0;32mexcept\u001b[0m \u001b[0mtimeout\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.5/site-packages/urllib3/contrib/pyopenssl.py\u001b[0m in \u001b[0;36mrecv_into\u001b[0;34m(self, *args, **kwargs)\u001b[0m\n\u001b[1;32m    293\u001b[0m         \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 294\u001b[0;31m             \u001b[0;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mconnection\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mrecv_into\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    295\u001b[0m         \u001b[0;32mexcept\u001b[0m \u001b[0mOpenSSL\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mSSL\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mSysCallError\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.5/site-packages/OpenSSL/SSL.py\u001b[0m in \u001b[0;36mrecv_into\u001b[0;34m(self, buffer, nbytes, flags)\u001b[0m\n\u001b[1;32m   1812\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1813\u001b[0;31m             \u001b[0mresult\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0m_lib\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mSSL_read\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_ssl\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mbuf\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mnbytes\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1814\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_raise_ssl_error\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_ssl\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mresult\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m: ",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;32m/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py\u001b[0m in \u001b[0;36mshowtraceback\u001b[0;34m(self, exc_tuple, filename, tb_offset, exception_only, running_compiled_code)\u001b[0m\n\u001b[1;32m   1862\u001b[0m                         \u001b[0;31m# in the engines. This should return a list of strings.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1863\u001b[0;31m                         \u001b[0mstb\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mvalue\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_render_traceback_\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1864\u001b[0m                     \u001b[0;32mexcept\u001b[0m \u001b[0mException\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mAttributeError\u001b[0m: 'KeyboardInterrupt' object has no attribute '_render_traceback_'",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py\u001b[0m in \u001b[0;36mrun_code\u001b[0;34m(self, code_obj, result)\u001b[0m\n\u001b[1;32m   2978\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mresult\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   2979\u001b[0m                 \u001b[0mresult\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0merror_in_exec\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0msys\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mexc_info\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m1\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 2980\u001b[0;31m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mshowtraceback\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mrunning_compiled_code\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mTrue\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   2981\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   2982\u001b[0m             \u001b[0moutflag\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;32mFalse\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py\u001b[0m in \u001b[0;36mshowtraceback\u001b[0;34m(self, exc_tuple, filename, tb_offset, exception_only, running_compiled_code)\u001b[0m\n\u001b[1;32m   1864\u001b[0m                     \u001b[0;32mexcept\u001b[0m \u001b[0mException\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1865\u001b[0m                         stb = self.InteractiveTB.structured_traceback(etype,\n\u001b[0;32m-> 1866\u001b[0;31m                                             value, tb, tb_offset=tb_offset)\n\u001b[0m\u001b[1;32m   1867\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1868\u001b[0m                     \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_showtraceback\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0metype\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mvalue\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mstb\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/local/lib/python3.5/dist-packages/IPython/core/ultratb.py\u001b[0m in \u001b[0;36mstructured_traceback\u001b[0;34m(self, etype, value, tb, tb_offset, number_of_lines_of_context)\u001b[0m\n\u001b[1;32m   1371\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtb\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mtb\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1372\u001b[0m         return FormattedTB.structured_traceback(\n\u001b[0;32m-> 1373\u001b[0;31m             self, etype, value, tb, tb_offset, number_of_lines_of_context)\n\u001b[0m\u001b[1;32m   1374\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1375\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/local/lib/python3.5/dist-packages/IPython/core/ultratb.py\u001b[0m in \u001b[0;36mstructured_traceback\u001b[0;34m(self, etype, value, tb, tb_offset, number_of_lines_of_context)\u001b[0m\n\u001b[1;32m   1279\u001b[0m             \u001b[0;31m# Verbose modes need a full traceback\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1280\u001b[0m             return VerboseTB.structured_traceback(\n\u001b[0;32m-> 1281\u001b[0;31m                 \u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0metype\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mvalue\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mtb\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mtb_offset\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mnumber_of_lines_of_context\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1282\u001b[0m             )\n\u001b[1;32m   1283\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/local/lib/python3.5/dist-packages/IPython/core/ultratb.py\u001b[0m in \u001b[0;36mstructured_traceback\u001b[0;34m(self, etype, evalue, etb, tb_offset, number_of_lines_of_context)\u001b[0m\n\u001b[1;32m   1142\u001b[0m         \u001b[0mexception\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget_parts_of_chained_exception\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mevalue\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1143\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mexception\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1144\u001b[0;31m             \u001b[0mformatted_exceptions\u001b[0m \u001b[0;34m+=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mprepare_chained_exception_message\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mevalue\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__cause__\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1145\u001b[0m             \u001b[0metype\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mevalue\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0metb\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mexception\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1146\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mTypeError\u001b[0m: Can't convert 'list' object to str implicitly"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/zmq/eventloop/zmqstream.py\", line 432, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/home/ubuntu/.local/lib/python3.5/site-packages/tornado/stack_context.py\", line 276, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py\", line 283, in dispatcher\n",
      "    return self.dispatch_shell(stream, msg)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py\", line 233, in dispatch_shell\n",
      "    handler(stream, idents, msg)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py\", line 421, in execute_request\n",
      "    self._abort_queues()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py\", line 636, in _abort_queues\n",
      "    self._abort_queue(stream)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py\", line 661, in _abort_queue\n",
      "    poller.poll(50)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/zmq/sugar/poll.py\", line 99, in poll\n",
      "    return zmq_poll(self.sockets, timeout=timeout)\n",
      "  File \"zmq/backend/cython/_poll.pyx\", line 123, in zmq.backend.cython._poll.zmq_poll\n",
      "  File \"zmq/backend/cython/checkrc.pxd\", line 12, in zmq.backend.cython.checkrc._check_rc\n",
      "KeyboardInterrupt\n"
     ]
    }
   ],
   "source": [
    "ift.main('tattoos')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.5.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
